package report

// SearchMetric 搜索指标
type SearchMetric struct {
	// OcpcConversions 目标转化量
	OcpcConversions int64 `json:"ocpcConversions,omitempty"`
	// DeepOCPCConversions 深度转化量
	DeepOCPCConversions int64 `json:"deepOCPCConversions,omitempty"`
	// TopPageViews 上方位展现
	TopPageViews int64 `json:"topPageViews,omitempty"`
	// TopPClicks 上方位点击
	TopPClicks int64 `json:"topPClicks,omitempty"`
	// TopPay 上方位消费
	TopPay int64 `json:"topPay,omitempty"`
	// TopPvWinA 上方展现胜出率
	// 【上方展现胜出率】与【推广业务】互斥并该指标不能与provinceCityName,cityName同时请求！
	// 上方展现胜出率=账户上方展现／账户符合投放条件的搜索次数
	TopPvWinA float64 `json:"topPvWinA,omitempty"`
	// TopPvWinP 上方展现胜出率（精确)
	// 【上方展现胜出率（精确）】与【推广业务】互斥 并该指标不能与provinceCityName,cityName同时请求！
	// 上方展现胜出率（精确）=账户精确触发的上方展现／账户符合投放条件&符合精确触发的搜索次数
	TopPvWinP float64 `json:"topPvWinP,omitempty"`
	// TopFirstPageViews 上方位首位展现
	TopFirstPageViews int64 `json:"topFirstPageViews,omitempty"`
	// TopFirstPvWinA 上方首位胜出率
	// 【上方首位胜出率】与【推广业务】互斥
	TopFirstPvWinA float64 `json:"topFirstPvWinA,omitempty"`
	// TopFirstWinP 上方首位胜出率（精确)
	// 【上方首位胜出率（精确）】与【推广业务】互斥
	TopFirstWinP float64 `json:"topFirstWinP,omitempty"`
	// 上方首位胜出率（精确)	该指标不能与同时请求！
	TopFirstPvWinP float64 `json:"topFirstPvWinP,omitempty"`
	// OcpcConversionsDetail1 咨询按钮点击量
	OcpcConversionsDetail1 int64 `json:"ocpcConversionsDetail1,omitempty"`
	// OcpcConversionsDetail1Cost 咨询按钮点击成本
	OcpcConversionsDetail1Cost float64 `json:"ocpcConversionsDetail1Cost,omitempty"`
	// OcpcConversionsDetail1CVR 咨询按钮点击转化率
	OcpcConversionsDetail1CVR float64 `json:"ocpcConversionsDetail1CVR,omitempty"`
	// OcpcConversionsDetail19 一句话咨询量
	OcpcConversionsDetail19 int64 `json:"ocpcConversionsDetail19,omitempty"`
	// OcpcConversionsDetail19Cost 一句话咨询成本
	OcpcConversionsDetail19Cost float64 `json:"ocpcConversionsDetail19Cost,omitempty"`
	// OcpcConversionsDetail19CVR 一句话咨询转化率
	OcpcConversionsDetail19CVR float64 `json:"ocpcConversionsDetail19CVR,omitempty"`
	// OcpcConversionsDetail17 三句话咨询量
	OcpcConversionsDetail17 int64 `json:"ocpcConversionsDetail17,omitempty"`
	// OcpcConversionsDetail17Cost 三句话咨询成本
	OcpcConversionsDetail17Cost float64 `json:"ocpcConversionsDetail17Cost,omitempty"`
	// OcpcConversionsDetail17CVR 三句话咨询转化率
	OcpcConversionsDetail17CVR float64 `json:"ocpcConversionsDetail17CVR,omitempty"`
	// OcpcConversionsDetail18 留线索量
	OcpcConversionsDetail18 int64 `json:"ocpcConversionsDetail18,omitempty"`
	// OcpcConversionsDetail18Cost 留线索成本
	OcpcConversionsDetail18Cost float64 `json:"ocpcConversionsDetail18Cost,omitempty"`
	// OcpcConversionsDetail18CVR 留线索转化率
	OcpcConversionsDetail18CVR float64 `json:"ocpcConversionsDetail18CVR,omitempty"`
	// OcpcConversionsDetail43 小程序线索量
	OcpcConversionsDetail43 int64 `json:"ocpcConversionsDetail43,omitempty"`
	// OcpcConversionsDetail43Cost 小程序线索成本
	OcpcConversionsDetail43Cost float64 `json:"ocpcConversionsDetail43Cost,omitempty"`
	// OcpcConversionsDetail43CVR 小程序线索转化率
	OcpcConversionsDetail43CVR float64 `json:"ocpcConversionsDetail43CVR,omitempty"`
	// OcpcConversionsDetail51 有意向客户量
	OcpcConversionsDetail51 int64 `json:"ocpcConversionsDetail51,omitempty"`
	// OcpcConversionsDetail51Cost 有意向客户成本
	OcpcConversionsDetail51Cost float64 `json:"ocpcConversionsDetail51Cost,omitempty"`
	// OcpcConversionsDetail51CVR 有意向客户转化率
	OcpcConversionsDetail51CVR float64 `json:"ocpcConversionsDetail51CVR,omitempty"`
	// OcpcConversionsDetail5 表单按钮点击量
	OcpcConversionsDetail5 int64 `json:"ocpcConversionsDetail5,omitempty"`
	// OcpcConversionsDetail5Cost 表单按钮点击成本
	OcpcConversionsDetail5Cost float64 `json:"ocpcConversionsDetail5Cost,omitempty"`
	// OcpcConversionsDetail5CVR 表单按钮点击转化率
	OcpcConversionsDetail5CVR float64 `json:"ocpcConversionsDetail5CVR,omitempty"`
	// OcpcConversionsDetail16 表单调起按钮点击量
	OcpcConversionsDetail16 int64 `json:"ocpcConversionsDetail16,omitempty"`
	// OcpcConversionsDetail16Cost 表单调起按钮点击成本
	OcpcConversionsDetail16Cost float64 `json:"ocpcConversionsDetail16Cost,omitempty"`
	// OcpcConversionsDetail16CVR 表单调起按钮点击转化率
	OcpcConversionsDetail16CVR float64 `json:"ocpcConversionsDetail16CVR,omitempty"`
	// OcpcConvertsionsDetail3 表单提交成功量
	OcpcConvertsionsDetail3 int64 `json:"ocpcConvertsionsDetail3,omitempty"`
	// OcpcConvertsionsDetail3Cost 表单提交成功成本
	OcpcConvertsionsDetail3Cost float64 `json:"ocpcConvertsionsDetail3Cost,omitempty"`
	// OcpcConvertsionsDetail3CVR 表单提交成功转化率
	OcpcConvertsionsDetail3CVR float64 `json:"ocpcConvertsionsDetail3CVR,omitempty"`
	// OcpcConversionsDetail2 电话按钮点击量
	OcpcConversionsDetail2 int64 `json:"ocpcConversionsDetail2,omitempty"`
	// OcpcConversionsDetail2Cost 电话按钮点击成本
	OcpcConversionsDetail2Cost float64 `json:"ocpcConversionsDetail2Cost,omitempty"`
	// OcpcConversionsDetail2CVR 电话按钮点击转化率
	OcpcConversionsDetail2CVR float64 `json:"ocpcConversionsDetail2CVR,omitempty"`
	// OcpcConversionsDetail30 电话拨通量
	OcpcConversionsDetail30 int64 `json:"ocpcConversionsDetail30,omitempty"`
	// OcpcConversionsDetail30Cost 电话拨通成本
	OcpcConversionsDetail30Cost float64 `json:"ocpcConversionsDetail30Cost,omitempty"`
	// OcpcConversionsDetail30CVR 电话拨通转化率
	OcpcConversionsDetail30CVR float64 `json:"ocpcConversionsDetail30CVR,omitempty"`
	// OcpcConversionsDetail35 微信复制按钮点击量
	OcpcConversionsDetail35 int64 `json:"ocpcConversionsDetail35,omitempty"`
	// OcpcConversionsDetail35Cost 微信复制按钮点击成本
	OcpcConversionsDetail35Cost float64 `json:"ocpcConversionsDetail35Cost,omitempty"`
	// OcpcConversionsDetail35CVR 微信复制按钮点击转化率
	OcpcConversionsDetail35CVR float64 `json:"ocpcConversionsDetail35CVR,omitempty"`
	// OcpcConversionsDetail32 QQ咨询按钮点击量
	OcpcConversionsDetail32 int64 `json:"ocpcConversionsDetail32,omitempty"`
	// OcpcConversionsDetail32Cost QQ咨询按钮点击成本
	OcpcConversionsDetail32Cost float64 `json:"ocpcConversionsDetail32Cost,omitempty"`
	// OcpcConversionsDetail32CVR QQ咨询按钮点击转化率
	OcpcConversionsDetail32CVR float64 `json:"ocpcConversionsDetail32CVR,omitempty"`
	// OcpcConversionsDetail7 购买按钮点击量
	OcpcConversionsDetail7 int64 `json:"ocpcConversionsDetail7,omitempty"`
	// OcpcConversionsDetail7Cost 购买按钮点击成本
	OcpcConversionsDetail7Cost float64 `json:"ocpcConversionsDetail7Cost,omitempty"`
	// OcpcConversionsDetail7CVR 购买按钮点击转化率
	OcpcConversionsDetail7CVR float64 `json:"ocpcConversionsDetail7CVR,omitempty"`
	// OcpcConversionsDetail10 服务购买成功量
	OcpcConversionsDetail10 int64 `json:"ocpcConversionsDetail10,omitempty"`
	// OcpcConversionsDetail10Cost 服务购买成功成本
	OcpcConversionsDetail10Cost float64 `json:"ocpcConversionsDetail10Cost,omitempty"`
	// OcpcConversionsDetail10CVR 服务购买成功转化率
	OcpcConversionsDetail10CVR float64 `json:"ocpcConversionsDetail10CVR,omitempty"`
	// OcpcConversionsDetail20 关键页面浏览量
	OcpcConversionsDetail20 int64 `json:"ocpcConversionsDetail20,omitempty"`
	// OcpcConversionsDetail20Cost 关键页面浏览成本
	OcpcConversionsDetail20Cost float64 `json:"ocpcConversionsDetail20Cost,omitempty"`
	// OcpcConversionsDetail20CVR 关键页面浏览转化率
	OcpcConversionsDetail20CVR float64 `json:"ocpcConversionsDetail20CVR,omitempty"`
	// OcpcConversionsDetail6 下载（预约）按钮点击量
	OcpcConversionsDetail6 int64 `json:"ocpcConversionsDetail6,omitempty"`
	// OcpcConversionsDetail6Cost 下载（预约）按钮点击成本
	OcpcConversionsDetail6Cost float64 `json:"ocpcConversionsDetail6Cost,omitempty"`
	// OcpcConversionsDetail6CVR 下载（预约）按钮点击转化率
	OcpcConversionsDetail6CVR float64 `json:"ocpcConversionsDetail6CVR,omitempty"`
	// OcpcConversionsDetail50 预约量
	OcpcConversionsDetail50 int64 `json:"ocpcConversionsDetail50,omitempty"`
	// OcpcConversionsDetail50Cost 预约成本
	OcpcConversionsDetail50Cost float64 `json:"ocpcConversionsDetail50Cost,omitempty"`
	// OcpcConversionsDetail50CVR 预约转化率
	OcpcConversionsDetail50CVR float64 `json:"ocpcConversionsDetail50CVR,omitempty"`
	// OcpcConversionsDetail41 申请量
	OcpcConversionsDetail41 int64 `json:"ocpcConversionsDetail41,omitempty"`
	// OcpcConversionsDetail41Cost 申请成本
	OcpcConversionsDetail41Cost float64 `json:"ocpcConversionsDetail41Cost,omitempty"`
	// OcpcConversionsDetail41CVR 申请转化率
	OcpcConversionsDetail41CVR float64 `json:"ocpcConversionsDetail41CVR,omitempty"`
	// OcpcConversionsDetail42 授信量
	OcpcConversionsDetail42 int64 `json:"ocpcConversionsDetail42,omitempty"`
	// OcpcConversionsDetail42Cost 授信成本
	OcpcConversionsDetail42Cost float64 `json:"ocpcConversionsDetail42Cost,omitempty"`
	// OcpcConversionsDetail42CVR 授信转化率
	OcpcConversionsDetail42CVR float64 `json:"ocpcConversionsDetail42CVR,omitempty"`
	// OcpcConversionsDetail89 放款量
	OcpcConversionsDetail89 int64 `json:"ocpcConversionsDetail89,omitempty"`
	// OcpcConversionsDetail89Cost 放款成本
	OcpcConversionsDetail89Cost float64 `json:"ocpcConversionsDetail89Cost,omitempty"`
	// OcpcConversionsDetail89CVR 放款转化率
	OcpcConversionsDetail89CVR float64 `json:"ocpcConversionsDetail89CVR,omitempty"`
	// OcpcConversionsDetail8 短信咨询按钮点击量
	OcpcConversionsDetail8 int64 `json:"ocpcConversionsDetail8,omitempty"`
	// OcpcConversionsDetail8Cost 短信咨询按钮点击成本
	OcpcConversionsDetail8Cost float64 `json:"ocpcConversionsDetail8Cost,omitempty"`
	// OcpcConversionsDetail8CVR 短信咨询按钮点击转化率
	OcpcConversionsDetail8CVR float64 `json:"ocpcConversionsDetail8CVR,omitempty"`
	// OcpcConversionsDetail31 地图按钮点击量
	OcpcConversionsDetail31 int64 `json:"ocpcConversionsDetail31,omitempty"`
	// OcpcConversionsDetail31Cost 地图按钮点击成本
	OcpcConversionsDetail31Cost float64 `json:"ocpcConversionsDetail31Cost,omitempty"`
	// OcpcConversionsDetail31CVR 地图按钮点击转化率
	OcpcConversionsDetail31CVR float64 `json:"ocpcConversionsDetail31CVR,omitempty"`
	// OcpcConversionsDetail33 抽奖按钮点击量
	OcpcConversionsDetail33 int64 `json:"ocpcConversionsDetail33,omitempty"`
	// OcpcConversionsDetail33Cost 抽奖按钮点击成本
	OcpcConversionsDetail33Cost float64 `json:"ocpcConversionsDetail33Cost,omitempty"`
	// OcpcConversionsDetail33CVR 抽奖按钮点击转化率
	OcpcConversionsDetail33CVR float64 `json:"ocpcConversionsDetail33CVR,omitempty"`
	// OcpcConversionsDetail12 预约按钮点击量
	OcpcConversionsDetail12 int64 `json:"ocpcConversionsDetail12,omitempty"`
	// OcpcConversionsDetail12Cost 预约按钮点击成本
	OcpcConversionsDetail12Cost float64 `json:"ocpcConversionsDetail12Cost,omitempty"`
	// OcpcConversionsDetail12CVR 预约按钮点击转化率
	OcpcConversionsDetail12CVR float64 `json:"ocpcConversionsDetail12CVR,omitempty"`
	// OcpcConversionsDetail34 投票按钮点击量
	OcpcConversionsDetail34 int64 `json:"ocpcConversionsDetail34,omitempty"`
	// OcpcConversionsDetail34Cost 投票按钮点击成本
	OcpcConversionsDetail34Cost float64 `json:"ocpcConversionsDetail34Cost,omitempty"`
	// OcpcConversionsDetail34CVR 投票按钮点击转化率
	OcpcConversionsDetail34CVR float64 `json:"ocpcConversionsDetail34CVR,omitempty"`
	// OcpcConversionsDetail36 评价按钮点击量
	OcpcConversionsDetail36 int64 `json:"ocpcConversionsDetail36,omitempty"`
	// OcpcConversionsDetail36Cost 评价按钮点击成本
	OcpcConversionsDetail36Cost float64 `json:"ocpcConversionsDetail36Cost,omitempty"`
	// OcpcConversionsDetail36CVR 评价按钮点击转化率
	OcpcConversionsDetail36CVR float64 `json:"ocpcConversionsDetail36CVR,omitempty"`
	// OcpcConversionsDetail40 关注按钮点击量
	OcpcConversionsDetail40 int64 `json:"ocpcConversionsDetail40,omitempty"`
	// OcpcConversionsDetail40Cost 关注按钮点击成本
	OcpcConversionsDetail40Cost float64 `json:"ocpcConversionsDetail40Cost,omitempty"`
	// OcpcConversionsDetail40CVR 关注按钮点击转化率
	OcpcConversionsDetail40CVR float64 `json:"ocpcConversionsDetail40CVR,omitempty"`
	// OcpcConversionsDetail57 店铺调起量
	OcpcConversionsDetail57 int64 `json:"ocpcConversionsDetail57,omitempty"`
	// OcpcConversionsDetail57Cost 店铺调起成本
	OcpcConversionsDetail57Cost float64 `json:"ocpcConversionsDetail57Cost,omitempty"`
	// OcpcConversionsDetail57CVR 店铺调起转化率
	OcpcConversionsDetail57CVR float64 `json:"ocpcConversionsDetail57CVR,omitempty"`
	// OcpcConversionsDetail68 粉丝关注成功量
	OcpcConversionsDetail68 int64 `json:"ocpcConversionsDetail68,omitempty"`
	// OcpcConversionsDetail68Cost 粉丝关注成功成本
	OcpcConversionsDetail68Cost float64 `json:"ocpcConversionsDetail68Cost,omitempty"`
	// OcpcConversionsDetail68CVR 粉丝关注成功转化率
	OcpcConversionsDetail68CVR float64 `json:"ocpcConversionsDetail68CVR,omitempty"`
	// OcpcConversionsDetail67 微信调起按钮点击量
	OcpcConversionsDetail67 int64 `json:"ocpcConversionsDetail67,omitempty"`
	// OcpcConversionsDetail67Cost 微信调起按钮点击成本
	OcpcConversionsDetail67Cost float64 `json:"ocpcConversionsDetail67Cost,omitempty"`
	// OcpcConversionsDetail67CVR 微信调起按钮点击转化率
	OcpcConversionsDetail67CVR float64 `json:"ocpcConversionsDetail67CVR,omitempty"`
	// OcpcConversionsDetail79 微信加粉成功量
	OcpcConversionsDetail79 int64 `json:"ocpcConversionsDetail79,omitempty"`
	// OcpcConversionsDetail79Cost 微信加粉成功成本
	OcpcConversionsDetail79Cost float64 `json:"ocpcConversionsDetail79Cost,omitempty"`
	// OcpcConversionsDetail79CVR 微信加粉成功转化率
	OcpcConversionsDetail79CVR float64 `json:"ocpcConversionsDetail79CVR,omitempty"`
	// OcpcConversionsDetail61 二次跳转量
	OcpcConversionsDetail61 int64 `json:"ocpcConversionsDetail61,omitempty"`
	// OcpcConversionsDetail61Cost 二次跳转成本
	OcpcConversionsDetail61Cost float64 `json:"ocpcConversionsDetail61Cost,omitempty"`
	// OcpcConversionsDetail61CVR 二次跳转转化率
	OcpcConversionsDetail61CVR float64 `json:"ocpcConversionsDetail61CVR,omitempty"`
	// OcpcConversionsDetail15 加入购物车按钮点击量
	OcpcConversionsDetail15 int64 `json:"ocpcConversionsDetail15,omitempty"`
	// OcpcConversionsDetail15Cost 加入购物车按钮点击成本
	OcpcConversionsDetail15Cost float64 `json:"ocpcConversionsDetail15Cost,omitempty"`
	// OcpcConversionsDetail15CVR 加入购物车按钮点击转化率
	OcpcConversionsDetail15CVR float64 `json:"ocpcConversionsDetail15CVR,omitempty"`
	// OcpcConversionsDetail46 加入购物车量
	OcpcConversionsDetail46 int64 `json:"ocpcConversionsDetail46,omitempty"`
	// OcpcConversionsDetail46Cost 加入购物车成本
	OcpcConversionsDetail46Cost float64 `json:"ocpcConversionsDetail46Cost,omitempty"`
	// OcpcConversionsDetail46CVR 加入购物车转化率
	OcpcConversionsDetail46CVR float64 `json:"ocpcConversionsDetail46CVR,omitempty"`
	// OcpcConversionsDetail9 电商订单量
	OcpcConversionsDetail9 int64 `json:"ocpcConversionsDetail9,omitempty"`
	// OcpcConversionsDetail9Cost 电商订单成本
	OcpcConversionsDetail9Cost float64 `json:"ocpcConversionsDetail9Cost,omitempty"`
	// OcpcConversionsDetail9CVR 电商订单转化率
	OcpcConversionsDetail9CVR float64 `json:"ocpcConversionsDetail9CVR,omitempty"`
	// OcpcConversionsDetail14 订单提交成功量
	OcpcConversionsDetail14 int64 `json:"ocpcConversionsDetail14,omitempty"`
	// OcpcConversionsDetail14Cost 订单提交成功成本
	OcpcConversionsDetail14Cost float64 `json:"ocpcConversionsDetail14Cost,omitempty"`
	// OcpcConversionsDetail14CVR 订单提交成功转化率
	OcpcConversionsDetail14CVR float64 `json:"ocpcConversionsDetail14CVR,omitempty"`
	// OcpcConversionsDetail14Amount 订单提交成功金额
	OcpcConversionsDetail14Amount float64 `json:"ocpcConversionsDetail14Amount,omitempty"`
	// OcpcConversionsDetail14AmountROI 订单提交成功金额ROI
	OcpcConversionsDetail14AmountROI float64 `json:"ocpcConversionsDetail14AmountROI,omitempty"`
	// OcpcConversionsDetail27 客户自定义转化量
	OcpcConversionsDetail27 int64 `json:"ocpcConversionsDetail27,omitempty"`
	// OcpcConversionsDetail27Cost 客户自定义转化成本
	OcpcConversionsDetail27Cost float64 `json:"ocpcConversionsDetail27Cost,omitempty"`
	// OcpcConversionsDetail27CVR 客户自定义转化率
	OcpcConversionsDetail27CVR float64 `json:"ocpcConversionsDetail27CVR,omitempty"`
	// OcpcConversionsDetail78 店铺停留转化量
	OcpcConversionsDetail78 int64 `json:"ocpcConversionsDetail78,omitempty"`
	// OcpcConversionsDetail78Cost 店铺停留转化成本
	OcpcConversionsDetail78Cost float64 `json:"ocpcConversionsDetail78Cost,omitempty"`
	// OcpcConversionsDetail78CVR 店铺停留转化率
	OcpcConversionsDetail78CVR float64 `json:"ocpcConversionsDetail78CVR,omitempty"`
	// OcpcConversionsDetail56 到店量
	OcpcConversionsDetail56 int64 `json:"ocpcConversionsDetail56,omitempty"`
	// OcpcConversionsDetail56Cost 到店成本
	OcpcConversionsDetail56Cost float64 `json:"ocpcConversionsDetail56Cost,omitempty"`
	// OcpcConversionsDetail56CVR 到店转化率
	OcpcConversionsDetail56CVR float64 `json:"ocpcConversionsDetail56CVR,omitempty"`
	// OcpcConversionsDetail90 商品支付成功量
	OcpcConversionsDetail90 int64 `json:"ocpcConversionsDetail90,omitempty"`
	// OcpcConversionsDetail90Cost 商品支付成功成本
	OcpcConversionsDetail90Cost float64 `json:"ocpcConversionsDetail90Cost,omitempty"`
	// OcpcConversionsDetail90CVR 商品支付成功转化率
	OcpcConversionsDetail90CVR float64 `json:"ocpcConversionsDetail90CVR,omitempty"`
	// OcpcConversionsDetail90Amount 商品支付成功金额
	OcpcConversionsDetail90Amount float64 `json:"ocpcConversionsDetail90Amount,omitempty"`
	// OcpcConversionsDetail90AmountROI 商品支付成功金额ROI
	OcpcConversionsDetail90AmountROI float64 `json:"ocpcConversionsDetail90AmountROI,omitempty"`
	// OcpcConversionsDetail92 有效咨询量
	OcpcConversionsDetail92 int64 `json:"ocpcConversionsDetail92,omitempty"`
	// OcpcConversionsDetail92Cost 有效咨询成本
	OcpcConversionsDetail92Cost float64 `json:"ocpcConversionsDetail92Cost,omitempty"`
	// OcpcConversionsDetail92CVR 有效咨询转化率
	OcpcConversionsDetail92CVR float64 `json:"ocpcConversionsDetail92CVR,omitempty"`
	// OcpcLandingPageConversionsDetail99 其他转化量(落地页)
	OcpcLandingPageConversionsDetail99 int64 `json:"ocpcLandingPageConversionsDetail99,omitempty"`
	// OcpcLandingPageConversionsDetail99Cost 其他转化成本
	OcpcLandingPageConversionsDetail99Cost float64 `json:"ocpcLandingPageConversionsDetail99Cost,omitempty"`
	// OcpcLandingPageConversionsDetail99CVR 其他转化率
	OcpcLandingPageConversionsDetail99CVR float64 `json:"ocpcLandingPageConversionsDetail99CVR,omitempty"`
	// OcpcConversionsDetail112 微信小程序调起人数
	OcpcConversionsDetail112 int64 `json:"oCPCConversionsDetail112,omitempty"`
	// OcpcConversionsDetail112Cost 微信小程序调起成本
	OcpcConversionsDetail112Cost float64 `json:"oCPCConversionsDetail112Cost,omitempty"`
	// OcpcConversionsDetail112CVR 微信小程序调起转化率
	OcpcConversionsDetail112CVR float64 `json:"oCPCConversionsDetail112CVR,omitempty"`
	// CtOCPCConversionsDetail1 咨询按钮点击量（转化时间）
	CtOCPCConversionsDetail1 int64 `json:"ctOCPCConversionsDetail1,omitempty"`
	// CtOCPCConversionsDetail19 一句话咨询量（转化时间）
	CtOCPCConversionsDetail19 int64 `json:"ctOCPCConversionsDetail19,omitempty"`
	// CtOCPCConversionsDetail17 三句话咨询量（转化时间）
	CtOCPCConversionsDetail17 int64 `json:"ctOCPCConversionsDetail17,omitempty"`
	// CtOCPCCOnversionsDetail18 留线索量（转化时间）
	CtOCPCCOnversionsDetail18 int64 `json:"ctOCPCCOnversionsDetail18,omitempty"`
	// CtOCPCConversionsDetail43 小程序线索量（转化时间）
	CtOCPCConversionsDetail43 int64 `json:"ctOCPCConversionsDetail43,omitempty"`
	// CtOCPCConversionsDetail51 有意向客户量（转化时间）
	CtOCPCConversionsDetail51 int64 `json:"ctOCPCConversionsDetail51,omitempty"`
	// CtOCPCConversionsDetail5 表单按钮点击量（转化时间）
	CtOCPCConversionsDetail5 int64 `json:"ctOCPCConversionsDetail5,omitempty"`
	// CtOCPCConversionsDetail16 表单调起按钮点击量（转化时间）
	CtOCPCConversionsDetail16 int64 `json:"ctOCPCConversionsDetail16,omitempty"`
	// CtOCPCConversionsDetail3 表单提交成功量（转化时间）
	CtOCPCConversionsDetail3 int64 `json:"ctOCPCConversionsDetail3,omitempty"`
	// CtOCPCConversionsDetail2 电话按钮点击量（转化时间）
	CtOCPCConversionsDetail2 int64 `json:"ctOCPCConversionsDetail2,omitempty"`
	// CtOCPCConversionsDetail30 电话拨通量（转化时间）
	CtOCPCConversionsDetail30 int64 `json:"ctOCPCConversionsDetail30,omitempty"`
	// CtOCPCConversionsDetail35 微信复制按钮点击量（转化时间）
	CtOCPCConversionsDetail35 int64 `json:"ctOCPCConversionsDetail35,omitempty"`
	// CtOCPCConversionsDetail32 QQ咨询按钮点击量（转化时间）
	CtOCPCConversionsDetail32 int64 `json:"ctOCPCConversionsDetail32,omitempty"`
	// CtOCPCConversionsDetail7 购买按钮点击量（转化时间）
	CtOCPCConversionsDetail7 int64 `json:"ctOCPCConversionsDetail7,omitempty"`
	// CtOCPCConversionsDetail10 服务购买成功量（转化时间）
	CtOCPCConversionsDetail10 int64 `json:"ctOCPCConversionsDetail10,omitempty"`
	// CtOCPCConversionsDetail20 关键页面浏览量（转化时间）
	CtOCPCConversionsDetail20 int64 `json:"ctOCPCConversionsDetail20,omitempty"`
	// CtOCPCConversionsDetail6 下载（预约）按钮点击量（转化时间）
	CtOCPCConversionsDetail6 int64 `json:"ctOCPCConversionsDetail6,omitempty"`
	// CtOCPCConversionsDetail50 预约量（转化时间）
	CtOCPCConversionsDetail50 int64 `json:"ctOCPCConversionsDetail50,omitempty"`
	// CtOCPCConversionsDetail41 申请量（转化时间）
	CtOCPCConversionsDetail41 int64 `json:"ctOCPCConversionsDetail41,omitempty"`
	// CtOCPCConversionsDetail42 授信量（转化时间）
	CtOCPCConversionsDetail42 int64 `json:"ctOCPCConversionsDetail42,omitempty"`
	// CtOCPCConversionsDetail89 放款量（转化时间）
	CtOCPCConversionsDetail89 int64 `json:"ctOCPCConversionsDetail89,omitempty"`
	// CtOCPCConversionsDetail8 短信咨询按钮点击量（转化时间）
	CtOCPCConversionsDetail8 int64 `json:"ctOCPCConversionsDetail8,omitempty"`
	// CtOCPCConversionsDetail31 地图按钮点击量（转化时间）
	CtOCPCConversionsDetail31 int64 `json:"ctOCPCConversionsDetail31,omitempty"`
	// CtOCPCConversionsDetail33 抽奖按钮点击量（转化时间）
	CtOCPCConversionsDetail33 int64 `json:"ctOCPCConversionsDetail33,omitempty"`
	// CtOCPCConversionsDetail12 预约按钮点击量（转化时间）
	CtOCPCConversionsDetail12 int64 `json:"ctOCPCConversionsDetail12,omitempty"`
	// CtOCPCConversionsDetail34 投票按钮点击量（转化时间）
	CtOCPCConversionsDetail34 int64 `json:"ctOCPCConversionsDetail34,omitempty"`
	// CtOCPCConversionsDetail36 评价按钮点击量（转化时间）
	CtOCPCConversionsDetail36 int64 `json:"ctOCPCConversionsDetail36,omitempty"`
	// CtOCPCConversionsDetail40 关注按钮点击量（转化时间）
	CtOCPCConversionsDetail40 int64 `json:"ctOCPCConversionsDetail40,omitempty"`
	// CtOCPCConversionsDetail57 店铺调起量（转化时间）
	CtOCPCConversionsDetail57 int64 `json:"ctOCPCConversionsDetail57,omitempty"`
	// CtOCPCConversionsDetail68 粉丝关注成功量（转化时间）
	CtOCPCConversionsDetail68 int64 `json:"ctOCPCConversionsDetail68,omitempty"`
	// CtOCPCConversionsDetail67 微信调起按钮点击量（转化时间）
	CtOCPCConversionsDetail67 int64 `json:"ctOCPCConversionsDetail67,omitempty"`
	// CtOCPCConversionsDetail79 微信加粉成功量（转化时间）
	CtOCPCConversionsDetail79 int64 `json:"ctOCPCConversionsDetail79,omitempty"`
	// CtOCPCConversionsDetail61 二次跳转量（转化时间）
	CtOCPCConversionsDetail61 int64 `json:"ctOCPCConversionsDetail61,omitempty"`
	// CtOCPCConversionsDetail15 加入购物车按钮点击量（转化时间）
	CtOCPCConversionsDetail15 int64 `json:"ctOCPCConversionsDetail15,omitempty"`
	// CtOCPCConversionsDetail46 	加入购物车量（转化时间）
	CtOCPCConversionsDetail46 int64 `json:"ctOCPCConversionsDetail46,omitempty"`
	// CtOCPCConversionsDetail9 电商订单量（转化时间）
	CtOCPCConversionsDetail9 int64 `json:"ctOCPCConversionsDetail9,omitempty"`
	// CtOCPCConversionsDetail14 	订单提交成功量（转化时间）
	CtOCPCConversionsDetail14 int64 `json:"ctOCPCConversionsDetail14,omitempty"`
	// CtOCPCConversionsDetail14Amount 订单提交成功金额（转化时间）
	CtOCPCConversionsDetail14Amount float64 `json:"ctOCPCConversionsDetail14Amount,omitempty"`
	// CtOCPCConversionsDetail14AmountROI 订单提交成功ROI（转化时间）
	CtOCPCConversionsDetail14AmountROI float64 `json:"ctOCPCConversionsDetail14AmountROI,omitempty"`
	// CtOCPCConversionsDetail27 客户自定义转化量（转化时间）
	CtOCPCConversionsDetail27 int64 `json:"ctOCPCConversionsDetail27,omitempty"`
	/// CtOCPCConversionsDetail78 店铺停留转化量（转化时间）
	CtOCPCConversionsDetail78 int64 `json:"ctOCPCConversionsDetail78,omitempty"`
	// CtOCPCConversionsDetail56 到店量（转化时间）
	CtOCPCConversionsDetail56 int64 `json:"ctOCPCConversionsDetail56,omitempty"`
	// CtOCPCConversionsDetail90	商品支付成功量（转化时间）
	CtOCPCConversionsDetail90 int64 `json:"ctOCPCConversionsDetail90,omitempty"`
	// CtOCPCConversionsDetail90Amount 商品支付成功金额（转化时间）
	CtOCPCConversionsDetail90Amount float64 `json:"ctOCPCConversionsDetail90Amount,omitempty"`
	// CtOCPCConversionsDetail90AmountROI 商品支付成功ROI（转化时间）
	CtOCPCConversionsDetail90AmountROI float64 `json:"ctOCPCConversionsDetail90AmountROI,omitempty"`
	// CtOCPCConversionsDetail92 有效咨询量（转化时间）
	CtOCPCConversionsDetail92 int64 `json:"ctOCPCConversionsDetail92,omitempty"`
	// CtOCPCLandingPageConversionsDetail99 其他转化量(落地页)（转化时间）
	CtOCPCLandingPageConversionsDetail99 int64 `json:"ctOCPCLandingPageConversionsDetail99,omitempty"`
	// CtOCPCConversionsDetail112 微信小程序调起人数（转化时间）
	CtOCPCConversionsDetail112 int64 `json:"ctOCPCConversionsDetail112,omitempty"`
	// OcpcConversionsDetail4 激活人数
	OcpcConversionsDetail4 int64 `json:"ocpcConversionsDetail4,omitempty"`
	// OcpcConversionsDetail4Cost 激活成本
	OcpcConversionsDetail4Cost float64 `json:"ocpcConversionsDetail4Cost,omitempty"`
	// OcpcConversionsDetail4CVR 激活转化率
	OcpcConversionsDetail4CVR float64 `json:"ocpcConversionsDetail4CVR,omitempty"`
	// OcpcConversionsDetail25 注册人数
	OcpcConversionsDetail25 int64 `json:"ocpcConversionsDetail25,omitempty"`
	// OcpcConversionsDetail25Cost 注册成本
	OcpcConversionsDetail25Cost float64 `json:"ocpcConversionsDetail25Cost,omitempty"`
	// OcpcConversionsDetail25CVR 注册转化率
	OcpcConversionsDetail25CVR float64 `json:"ocpcConversionsDetail25CVR,omitempty"`
	// OcpcConversionsDetail26 付费人数
	OcpcConversionsDetail26 int64 `json:"ocpcConversionsDetail26,omitempty"`
	// OcpcConversionsDetail26Cost 付费成本
	OcpcConversionsDetail26Cost float64 `json:"ocpcConversionsDetail26Cost,omitempty"`
	// OcpcConversionsDetail26CVR 付费转化率
	OcpcConversionsDetail26CVR float64 `json:"ocpcConversionsDetail26CVR,omitempty"`
	// OcpcConversionsDetail45 商品下单成功量
	OcpcConversionsDetail45 int64 `json:"ocpcConversionsDetail45,omitempty"`
	// OcpcConversionsDetail45Cost 商品下单成功成本
	OcpcConversionsDetail45Cost float64 `json:"ocpcConversionsDetail45Cost,omitempty"`
	// OcpcConversionsDetail45CVR 商品下单成功转化率
	OcpcConversionsDetail45CVR float64 `json:"ocpcConversionsDetail45CVR,omitempty"`
	// OcpcConversionsDetail52 深度使用量
	OcpcConversionsDetail52 int64 `json:"ocpcConversionsDetail52,omitempty"`
	// OcpcConversionsDetail52Cost 深度使用成本
	OcpcConversionsDetail52Cost float64 `json:"ocpcConversionsDetail52Cost,omitempty"`
	// OcpcConversionsDetail52CVR 深度使用转化率
	OcpcConversionsDetail52CVR float64 `json:"ocpcConversionsDetail52CVR,omitempty"`
	// OcpcConversionsDetail28 次日留存人数
	OcpcConversionsDetail28 int64 `json:"ocpcConversionsDetail28,omitempty"`
	// OcpcConversionsDetail28Cost 次日留存成本
	OcpcConversionsDetail28Cost float64 `json:"ocpcConversionsDetail28Cost,omitempty"`
	// OcpcConversionsDetail28CVR 次日留存转化率
	OcpcConversionsDetail28CVR float64 `json:"ocpcConversionsDetail28CVR,omitempty"`
	// OcpcConversionsDetail49 登录人数
	OcpcConversionsDetail49 int64 `json:"ocpcConversionsDetail49,omitempty"`
	// OcpcConversionsDetail49Cost 登录成本
	OcpcConversionsDetail49Cost float64 `json:"ocpcConversionsDetail49Cost,omitempty"`
	// OcpcConversionsDetail49CVR 登录转化率
	OcpcConversionsDetail49CVR float64 `json:"ocpcConversionsDetail49CVR,omitempty"`
	// OcpcConversionsDetail71 应用调起人数
	OcpcConversionsDetail71 int64 `json:"ocpcConversionsDetail71,omitempty"`
	// OcpcConversionsDetail71Cost 应用调起成本
	OcpcConversionsDetail71Cost float64 `json:"ocpcConversionsDetail71Cost,omitempty"`
	// OcpcConversionsDetail71CVR 应用调起转化率
	OcpcConversionsDetail71CVR float64 `json:"ocpcConversionsDetail71CVR,omitempty"`
	// OcpcConversionsDetail26One 激活当日付费金额
	OcpcConversionsDetail26One float64 `json:"ocpcConversionsDetail26One,omitempty"`
	// OcpcConversionsDetail26Three 激活3日内付费金额
	OcpcConversionsDetail26Three float64 `json:"ocpcConversionsDetail26Three,omitempty"`
	// OcpcConversionsDetail26Seven 激活7日内付费金额
	OcpcConversionsDetail26Seven float64 `json:"ocpcConversionsDetail26Seven,omitempty"`
	// OcpcConversionsDetail26Fourteen 激活14日内付费金额
	OcpcConversionsDetail26Fourteen float64 `json:"ocpcConversionsDetail26Fourteen,omitempty"`
	// OcpcConversionsDetail26Thirty 激活30日内付费金额
	OcpcConversionsDetail26Thirty float64 `json:"ocpcConversionsDetail26Thirty,omitempty"`
	// OcpcConversionsDetail26OneROI 激活当日付费ROI
	OcpcConversionsDetail26OneROI float64 `json:"ocpcConversionsDetail26OneROI,omitempty"`
	// OcpcConversionsDetail26ThreeROI 激活3日内付费ROI
	OcpcConversionsDetail26ThreeROI float64 `json:"ocpcConversionsDetail26ThreeROI,omitempty"`
	// OcpcConversionsDetail26SevenROI 激活7日内付费ROI
	OcpcConversionsDetail26SevenROI float64 `json:"ocpcConversionsDetail26SevenROI,omitempty"`
	// OcpcConversionsDetail26FourteenROI 激活14日内付费ROI
	OcpcConversionsDetail26FourteenROI float64 `json:"ocpcConversionsDetail26FourteenROI,omitempty"`
	// OcpcConversionsDetail26ThirtyROI 激活30日内付费ROI
	OcpcConversionsDetail26ThirtyROI float64 `json:"ocpcConversionsDetail26ThirtyROI,omitempty"`
	// OcpcAppConversionsDetail99 其他转化量(APP)
	OcpcAppConversionsDetail99 int64 `json:"ocpcAppConversionsDetail99,omitempty"`
	// OcpcAppConversionsDetail99Cost 其他转化成本(APP)
	OcpcAppConversionsDetail99Cost float64 `json:"ocpcAppConversionsDetail99Cost,omitempty"`
	// OcpcAppConversionsDetail99CVR 其他转化率(APP)
	OcpcAppConversionsDetail99CVR float64 `json:"ocpcAppConversionsDetail99CVR,omitempty"`
	// OcpcConversionsDetail28_49Rate 登录次日留存率
	OcpcConversionsDetail28_49Rate float64 `json:"oCPCConversionsDetail28_49Rate,omitempty"`
	// CtOCPCConvertsionsDetai4 激活人数（转化时间）
	CtOCPCConvertsionsDetai4 int64 `json:"ctOCPCConvertsionsDetai4,omitempty"`
	// CtOCPCConversionsDetail25 注册人数（转化时间）
	CtOCPCConversionsDetail25 int64 `json:"ctOCPCConversionsDetail25,omitempty"`
	// CtOCPCConversionsDetail26 付费人数（转化时间）
	CtOCPCConversionsDetail26 int64 `json:"ctOCPCConversionsDetail26,omitempty"`
	// CtOCPCConversionsDetail45 商品下单成功量（转化时间）
	CtOCPCConversionsDetail45 int64 `json:"ctOCPCConversionsDetail45,omitempty"`
	// CtOCPCConversionsDetail52 深度使用量（转化时间）
	CtOCPCConversionsDetail52 int64 `json:"ctOCPCConversionsDetail52,omitempty"`
	// CtOCPCConversionsDetail28 次日留存人数（转化时间）
	CtOCPCConversionsDetail28 int64 `json:"ctOCPCConversionsDetail28,omitempty"`
	// CtOCPCConversionsDetail49 登录人数（转化时间）
	CtOCPCConversionsDetail49 int64 `json:"ctOCPCConversionsDetail49,omitempty"`
	// CtOCPCConversionsDetail71 应用调起人数（转化时间）
	CtOCPCConversionsDetail71 int64 `json:"ctOCPCConversionsDetail71,omitempty"`
	// CtOCPCConversionsDetail26One 激活当日付费金额（转化时间）
	CtOCPCConversionsDetail26One float64 `json:"ctOCPCConversionsDetail26One,omitempty"`
	// CtOCPCConversionsDetail26Three 激活3日内付费金额（转化时间）
	CtOCPCConversionsDetail26Three float64 `json:"ctOCPCConversionsDetail26Three,omitempty"`
	// CtOCPCConversionsDetail26Seven 激活7日内付费金额（转化时间）
	CtOCPCConversionsDetail26Seven float64 `json:"ctOCPCConversionsDetail26Seven,omitempty"`
	// CtOCPCConversionsDetail26Fourteen 激活14日内付费金额（转化时间）
	CtOCPCConversionsDetail26Fourteen float64 `json:"ctOCPCConversionsDetail26Fourteen,omitempty"`
	// CtOCPCConversionsDetail26Thirty 激活30日内付费金额（转化时间）
	CtOCPCConversionsDetail26Thirty float64 `json:"ctOCPCConversionsDetail26Thirty,omitempty"`
	// CtOCPCConversionsDetail26OneROI 激活当日付费ROI（转化时间）
	CtOCPCConversionsDetail26OneROI float64 `json:"ctOCPCConversionsDetail26OneROI,omitempty"`
	// CtOCPCConversionsDetail26ThreeROI 激活3日内付费ROI（转化时间）
	CtOCPCConversionsDetail26ThreeROI float64 `json:"ctOCPCConversionsDetail26ThreeROI,omitempty"`
	// CtOCPCConversionsDetail26SevenROI 激活7日内付费ROI（转化时间）
	CtOCPCConversionsDetail26SevenROI float64 `json:"ctOCPCConversionsDetail26SevenROI,omitempty"`
	// CtOCPCConversionsDetail26FourteenROI 激活14日内付费ROI（转化时间）
	CtOCPCConversionsDetail26FourteenROI float64 `json:"ctOCPCConversionsDetail26FourteenROI,omitempty"`
	// CtOCPCConversionsDetail26ThirtyROI 激活30日内付费ROI（转化时间）
	CtOCPCConversionsDetail26ThirtyROI float64 `json:"ctOCPCConversionsDetail26ThirtyROI,omitempty"`
	// CtOCPCAppConversionsDetail99 其他转化量(APP)（转化时间）
	CtOCPCAppConversionsDetail99 int64 `json:"ctOCPCAppConversionsDetail99,omitempty"`
	// CtOCPCConversionsDetail28_49Rate 登录次日留存率（转化时间）
	CtOCPCConversionsDetail28_49Rate float64 `json:"ctOCPCConversionsDetail28_49Rate,omitempty"`

	// 11-04补充  场景转化指标-线索收集
	// CplConversions 服务直达线索量
	CplConversions int64 `json:"cplConversions,omitempty"`
	// CplConversionsCost 服务直达线索量平均成本
	CplConversionsCost int64 `json:"cplConversionsCost,omitempty"`
	// RfqConversions 线索加油包线索量
	RfqConversions int64 `json:"rfqConversions,omitempty"`
	// RfqConversionsCost 线索加油包线索成本
	RfqConversionsCost int64 `json:"rfqConversionsCost,omitempty"`
	// OcpcConversionsDetail1TransWorth 咨询按钮点击量转化价值
	OcpcConversionsDetail1TransWorth int64 `json:"ocpcConversionsDetail1TransWorth,omitempty"`
	// OcpcConversionsDetail51TransWorth 有意向客户量转化价值
	OcpcConversionsDetail51TransWorth int64 `json:"ocpcConversionsDetail51TransWorth,omitempty"`
	// OcpcConversionsDetail72 聊到相关业务
	OcpcConversionsDetail72 int64 `json:"ocpcConversionsDetail72,omitempty"`
	// OcpcConversionsDetail73 回访-电话接通量
	OcpcConversionsDetail73 int64 `json:"ocpcConversionsDetail73,omitempty"`
	// OcpcConversionsDetail73TransWorth 回访-电话接通量转化价值
	OcpcConversionsDetail73TransWorth float64 `json:"ocpcConversionsDetail73TransWorth,omitempty"`
	// OcpcConversionsDetail74 回访-信息确认量
	OcpcConversionsDetail74 int64 `json:"ocpcConversionsDetail74,omitempty"`
	// OcpcConversionsDetail74TransWorth 回访-信息确认量转化价值
	OcpcConversionsDetail74TransWorth int64 `json:"ocpcConversionsDetail74TransWorth,omitempty"`
	// OcpcConversionsDetail75 回访-发现意向量
	OcpcConversionsDetail75 int64 `json:"ocpcConversionsDetail75,omitempty"`
	// OcpcConversionsDetail75TransWorth 回访-发现意向量转化价值
	OcpcConversionsDetail75TransWorth int64 `json:"ocpcConversionsDetail75TransWorth,omitempty"`
	// OcpcConversionsDetail76 回访-高潜成交量
	OcpcConversionsDetail76 int64 `json:"ocpcConversionsDetail76,omitempty"`
	// OcpcConversionsDetail76TransWorth 回访-高潜成交量转化价值
	OcpcConversionsDetail76TransWorth int64 `json:"ocpcConversionsDetail76TransWorth,omitempty"`
	// OcpcConversionsDetail77 回访-成单客户量
	OcpcConversionsDetail77 int64 `json:"ocpcConversionsDetail77,omitempty"`
	// OcpcConversionsDetail77TransWorth 回访-成单客户量转化价值
	OcpcConversionsDetail77TransWorth int64 `json:"ocpcConversionsDetail77TransWorth,omitempty"`
	// OcpcConversionsDetail3 表单提交成功量
	OcpcConversionsDetail3 int64 `json:"ocpcConversionsDetail3,omitempty"`
	// OcpcConversionsDetail3TransWorth 表单提交成功量转化价值
	OcpcConversionsDetail3TransWorth int64 `json:"ocpcConversionsDetail3TransWorth,omitempty"`
	// OcpcConversionsDetail2TransWorth 电话按钮点击量转化价值
	OcpcConversionsDetail2TransWorth int64 `json:"ocpcConversionsDetail2TransWorth,omitempty"`
	// OcpcConversionsDetail120 综合线索收集
	OcpcConversionsDetail120 int64 `json:"ocpcConversionsDetail120,omitempty"`
	// OcpcConversionsDetail120_3 综合线索收集（表单提交成功）
	OcpcConversionsDetail120_3 int64 `json:"ocpcConversionsDetail120_3,omitempty"`
	// OcpcConversionsDetail120_18 综合线索收集（留线索）
	OcpcConversionsDetail120_18 int64 `json:"ocpcConversionsDetail120_18,omitempty"`
	// OcpcConversionsDetail120_30 综合线索收集（电话拨通）
	OcpcConversionsDetail120_30 int64 `json:"ocpcConversionsDetail120_30,omitempty"`
	// OCPCConversionsDetail112 微信小程序调起人数
	OCPCConversionsDetail112 int64 `json:"oCPCConversionsDetail112,omitempty"`
	// OcpcConversionsDetail141 挂号量
	OcpcConversionsDetail141 int64 `json:"ocpcConversionsDetail141,omitempty"`
	// OcpcConversionsDetail142 意向咨询量
	OcpcConversionsDetail142 int64 `json:"ocpcConversionsDetail142,omitempty"`
	// OcpcConversionsDetail143 意向表单量
	OcpcConversionsDetail143 int64 `json:"ocpcConversionsDetail143,omitempty"`
	// CtOCPCConversionsDetail1TransWorth 咨询按钮点击量转化价值（转化时间）
	CtOCPCConversionsDetail1TransWorth int64 `json:"ctOCPCConversionsDetail1TransWorth,omitempty"`
	// CtOCPCConversionsDetail18 留线索量（转化时间）
	CtOCPCConversionsDetail18 int64 `json:"ctOCPCConversionsDetail18,omitempty"`
	// CtOCPCConversionsDetail72 聊到相关业务（转化时间）
	CtOCPCConversionsDetail72 int64 `json:"ctOCPCConversionsDetail72,omitempty"`
	// CtOCPCConversionsDetail73 回访-电话接通量（转化时间）
	CtOCPCConversionsDetail73 int64 `json:"ctOCPCConversionsDetail73,omitempty"`
	// CtOCPCConversionsDetail73TransWorth 回访-电话接通量转化价值（转化时间）
	CtOCPCConversionsDetail73TransWorth int64 `json:"ctOCPCConversionsDetail73TransWorth,omitempty"`
	// CtOCPCConversionsDetail74 回访-信息确认量（转化时间）
	CtOCPCConversionsDetail74 int64 `json:"ctOCPCConversionsDetail74,omitempty"`
	// CtOCPCConversionsDetail74TransWorth 回访-信息确认量转化价值（转化时间）
	CtOCPCConversionsDetail74TransWorth int64 `json:"ctOCPCConversionsDetail74TransWorth,omitempty"`
	// CtOCPCConversionsDetail75 回访-发现意向量（转化时间）
	CtOCPCConversionsDetail75 int64 `json:"ctOCPCConversionsDetail75,omitempty"`
	// CtOCPCConversionsDetail75TransWorth 回访-发现意向量转化价值（转化时间）
	CtOCPCConversionsDetail75TransWorth int64 `json:"ctOCPCConversionsDetail75TransWorth,omitempty"`
	// CtOCPCConversionsDetail76 回访-高潜成交量（转化时间）
	CtOCPCConversionsDetail76 int64 `json:"ctOCPCConversionsDetail76,omitempty"`
	// CtOCPCConversionsDetail76TransWorth 回访-高潜成交量转化价值（转化时间）
	CtOCPCConversionsDetail76TransWorth int64 `json:"ctOCPCConversionsDetail76TransWorth,omitempty"`
	// CtOCPCConversionsDetail77 回访-成单客户量（转化时间）
	CtOCPCConversionsDetail77 int64 `json:"ctOCPCConversionsDetail77,omitempty"`
	// CtOCPCConversionsDetail77TransWorth 回访-成单客户量转化价值（转化时间）
	CtOCPCConversionsDetail77TransWorth int64 `json:"ctOCPCConversionsDetail77TransWorth,omitempty"`
	// CtOCPCConversionsDetail51TransWorth 有意向客户量转化价值（转化时间）
	CtOCPCConversionsDetail51TransWorth int64 `json:"ctOCPCConversionsDetail51TransWorth,omitempty"`
	// CtOCPCConversionsDetail3TransWorth 表单提交成功量转化价值（转化时间）
	CtOCPCConversionsDetail3TransWorth int64 `json:"ctOCPCConversionsDetail3TransWorth,omitempty"`
	// CtOCPCConversionsDetail2TransWorth 电话按钮点击量转化价值（转化时间）
	CtOCPCConversionsDetail2TransWorth int64 `json:"ctOCPCConversionsDetail2TransWorth,omitempty"`
	// CtOCPCConversionsDetail120 综合线索收集（转化时间）
	CtOCPCConversionsDetail120 int64 `json:"ctOCPCConversionsDetail120,omitempty"`
	// CtOCPCConversionsDetail120_3 综合线索收集（表单提交成功）（转化时间）
	CtOCPCConversionsDetail120_3 int64 `json:"ctOCPCConversionsDetail120_3,omitempty"`
	// CtOCPCConversionsDetail120_18 综合线索收集（留线索）（转化时间）
	CtOCPCConversionsDetail120_18 int64 `json:"ctOCPCConversionsDetail120_18,omitempty"`
	// CtOCPCConversionsDetail120_30 综合线索收集（电话拨通）（转化时间）
	CtOCPCConversionsDetail120_30 int64 `json:"ctOCPCConversionsDetail120_30,omitempty"`
	// CtOCPCConversionsDetail141 挂号量（转化时间）
	CtOCPCConversionsDetail141 int64 `json:"ctOCPCConversionsDetail141,omitempty"`
	// CtOCPCConversionsDetail142 意向咨询量（转化时间）
	CtOCPCConversionsDetail142 int64 `json:"ctOCPCConversionsDetail142,omitempty"`
	// CtOCPCConversionsDetail143 意向表单量（转化时间）
	CtOCPCConversionsDetail143 int64 `json:"ctOCPCConversionsDetail143,omitempty"`

	// 11-04补充  场景转化指标-产品订购
	// OcpcConversionsDetail10TransWorth 服务购买成功转化价值
	OcpcConversionsDetail10TransWorth int64 `json:"ocpcConversionsDetail10TransWorth,omitempty"`
	// OcpcConversionsDetail14TransWorth 订单提交成功转化价值
	OcpcConversionsDetail14TransWorth float64 `json:"ocpcConversionsDetail14TransWorth,omitempty"`
	// CtOCPCConversionsDetail10TransWorth 服务购买成功转化价值（转化时间）
	CtOCPCConversionsDetail10TransWorth int64 `json:"ctOCPCConversionsDetail10TransWorth,omitempty"`
	// CtOCPCConversionsDetail14TransWorth 订单提交成功转化价值（转化时间）
	CtOCPCConversionsDetail14TransWorth float64 `json:"ctOCPCConversionsDetail14TransWorth,omitempty"`

	// 11-04补充  场景转化指标-应用推广
	// OcpcConversionsDetail20TransWorth 关键页面浏览量转化价值
	OcpcConversionsDetail20TransWorth int64 `json:"ocpcConversionsDetail20TransWorth,omitempty"`
	// CtOCPCConversionsDetail20TransWorth 关键页面浏览量转化价值（转化时间）
	CtOCPCConversionsDetail20TransWorth int64 `json:"ctOCPCConversionsDetail20TransWorth,omitempty"`
	// OcpcConversionsDetail4TransWorth 激活人数转化价值
	OcpcConversionsDetail4TransWorth int64 `json:"ocpcConversionsDetail4TransWorth,omitempty"`
	// OcpcConversionsDetail25TransWorth 注册人数转化价值
	OcpcConversionsDetail25TransWorth int64 `json:"ocpcConversionsDetail25TransWorth,omitempty"`
	// OcpcConversionsDetail29 7日留存人数
	OcpcConversionsDetail29 int64 `json:"ocpcConversionsDetail29,omitempty"`
	// OcpcConversionsDetail95 3日留存人数
	OcpcConversionsDetail95 int64 `json:"ocpcConversionsDetail95,omitempty"`
	// OcpcConversionsDetail96 4日留存人数
	OcpcConversionsDetail96 int64 `json:"ocpcConversionsDetail96,omitempty"`
	// OcpcConversionsDetail97 5日留存人数
	OcpcConversionsDetail97 int64 `json:"ocpcConversionsDetail97,omitempty"`
	// OcpcConversionsDetail98 6日留存人数
	OcpcConversionsDetail98 int64 `json:"ocpcConversionsDetail98,omitempty"`
	// OcpcConversionsDetail100 14日留存人数
	OcpcConversionsDetail100 int64 `json:"ocpcConversionsDetail100,omitempty"`
	// OcpcConversionsDetail121 2日留存人数
	OcpcConversionsDetail121 int64 `json:"ocpcConversionsDetail121,omitempty"`
	// CtOCPCConversionsDetail4 激活人数（转化时间）
	CtOCPCConversionsDetail4 int64 `json:"ctOCPCConversionsDetail4,omitempty"`
	// CtOCPCConversionsDetail4TransWorth 激活人数转化价值（转化时间）
	CtOCPCConversionsDetail4TransWorth int64 `json:"ctOCPCConversionsDetail4TransWorth,omitempty"`
	// CtOCPCConversionsDetail25TransWorth 注册人数转化价值（转化时间）
	CtOCPCConversionsDetail25TransWorth int64 `json:"ctOCPCConversionsDetail25TransWorth,omitempty"`
	// CtOCPCConversionsDetail29 7日留存人数（转化时间）
	CtOCPCConversionsDetail29 int64 `json:"ctOCPCConversionsDetail29,omitempty"`
	// CtOCPCConversionsDetail95 3日留存人数（转化时间）
	CtOCPCConversionsDetail95 int64 `json:"ctOCPCConversionsDetail95,omitempty"`
	// CtOCPCConversionsDetail96 4日留存人数（转化时间）
	CtOCPCConversionsDetail96 int64 `json:"ctOCPCConversionsDetail96,omitempty"`
	// CtOCPCConversionsDetail97 5日留存人数（转化时间）
	CtOCPCConversionsDetail97 int64 `json:"ctOCPCConversionsDetail97,omitempty"`
	// CtOCPCConversionsDetail98 6日留存人数（转化时间）
	CtOCPCConversionsDetail98 int64 `json:"ctOCPCConversionsDetail98,omitempty"`
	// CtOCPCConversionsDetail100 14日留存人数（转化时间）
	CtOCPCConversionsDetail100 int64 `json:"ctOCPCConversionsDetail100,omitempty"`
	// CtOCPCConversionsDetail121 2日留存人数（转化时间）
	CtOCPCConversionsDetail121 int64 `json:"ctOCPCConversionsDetail121,omitempty"`

	// 11-04补充  行业转化指标-金融行业
	// OcpcConversionsDetail117 进件量
	OcpcConversionsDetail117 int64 `json:"ocpcConversionsDetail117,omitempty"`
	// OcpcConversionsDetail41TransWorth 申请量转化价值
	OcpcConversionsDetail41TransWorth int64 `json:"ocpcConversionsDetail41TransWorth,omitempty"`
	// CtOCPCConversionsDetail117 进件量（转化时间）
	CtOCPCConversionsDetail117 int64 `json:"ctOCPCConversionsDetail117,omitempty"`
	// CtOCPCConversionsDetail41TransWorth 申请量转化价值（转化时间）
	CtOCPCConversionsDetail41TransWorth int64 `json:"ctOCPCConversionsDetail41TransWorth,omitempty"`
	// OcpcConversionsDetail71TransWorth 应用调起人数转化价值
	OcpcConversionsDetail71TransWorth int64 `json:"ocpcConversionsDetail71TransWorth,omitempty"`
	// CtOCPCConversionsDetail71TransWorth 应用调起人数转化价值（转化时间）
	CtOCPCConversionsDetail71TransWorth int64 `json:"ctOCPCConversionsDetail71TransWorth,omitempty"`

	// 11-04补充  行业转化指标-游戏行业
	// OcpcConversionsDetail26_49One 登录当日付费金额
	OcpcConversionsDetail26_49One float64 `json:"ocpcConversionsDetail26_49One,omitempty"`
	// OcpcConversionsDetail26_49Three 登录3日内付费金额
	OcpcConversionsDetail26_49Three float64 `json:"ocpcConversionsDetail26_49Three,omitempty"`
	// OcpcConversionsDetail26_49Seven 登录7日内付费金额
	OcpcConversionsDetail26_49Seven float64 `json:"ocpcConversionsDetail26_49Seven,omitempty"`
	// CtOCPCConversionsDetail26_49One 登录当日付费金额（转化时间）
	CtOCPCConversionsDetail26_49One float64 `json:"ctOCPCConversionsDetail26_49One,omitempty"`
	// CtOCPCConversionsDetail26_49Three 登录3日内付费金额（转化时间）
	CtOCPCConversionsDetail26_49Three float64 `json:"ctOCPCConversionsDetail26_49Three,omitempty"`
	// CtOCPCConversionsDetail26_49Seven 登录7日内付费金额（转化时间）
	CtOCPCConversionsDetail26_49Seven float64 `json:"ctOCPCConversionsDetail26_49Seven,omitempty"`
	// OcpcConversionsDetail26TransWorth 付费人数转化价值
	OcpcConversionsDetail26TransWorth int64 `json:"ocpcConversionsDetail26TransWorth,omitempty"`
	// OcpcConversionsDetail26Count 付费次数
	OcpcConversionsDetail26Count int64 `json:"ocpcConversionsDetail26Count,omitempty"`
	// OcpcConversionsDetail49TransWorth 登录人数转化价值
	OcpcConversionsDetail49TransWorth int64 `json:"ocpcConversionsDetail49TransWorth,omitempty"`
	// CtOCPCConversionsDetail26TransWorth 付费人数转化价值（转化时间）
	CtOCPCConversionsDetail26TransWorth int64 `json:"ctOCPCConversionsDetail26TransWorth,omitempty"`
	// CtOCPCConversionsDetail26Count 付费次数（转化时间）
	CtOCPCConversionsDetail26Count int64 `json:"ctOCPCConversionsDetail26Count,omitempty"`
	// CtOCPCConversionsDetail49TransWorth 登录人数转化价值（转化时间）
	CtOCPCConversionsDetail49TransWorth int64 `json:"ctOCPCConversionsDetail49TransWorth,omitempty"`

	// 11-04补充  行业转化指标-文娱行业
	// OcpcConversionsDetail118 付费观剧人数
	OcpcConversionsDetail118 int64 `json:"ocpcConversionsDetail118,omitempty"`
	// OcpcConversionsDetail118One 付费观剧当日金额
	OcpcConversionsDetail118One float64 `json:"ocpcConversionsDetail118One,omitempty"`
	// OcpcConversionsDetail118Three 付费观剧3日金额
	OcpcConversionsDetail118Three float64 `json:"ocpcConversionsDetail118Three,omitempty"`
	// OcpcConversionsDetail118Seven 付费观剧7日金额
	OcpcConversionsDetail118Seven float64 `json:"ocpcConversionsDetail118Seven,omitempty"`
	// OcpcConversionsDetail118Fourteen 付费观剧14日金额
	OcpcConversionsDetail118Fourteen float64 `json:"ocpcConversionsDetail118Fourteen,omitempty"`
	// OcpcConversionsDetail118Thirty 付费观剧30日金额
	OcpcConversionsDetail118Thirty float64 `json:"ocpcConversionsDetail118Thirty,omitempty"`
	// CtOCPCConversionsDetail118 付费观剧人数（转化时间）
	CtOCPCConversionsDetail118 int64 `json:"ctOCPCConversionsDetail118,omitempty"`
	// CtOCPCConversionsDetail118One 付费观剧当日金额（转化时间）
	CtOCPCConversionsDetail118One float64 `json:"ctOCPCConversionsDetail118One,omitempty"`
	// CtOCPCConversionsDetail118Three 付费观剧3日金额（转化时间）
	CtOCPCConversionsDetail118Three float64 `json:"ctOCPCConversionsDetail118Three,omitempty"`
	// CtOCPCConversionsDetail118Seven 付费观剧7日金额（转化时间）
	CtOCPCConversionsDetail118Seven float64 `json:"ctOCPCConversionsDetail118Seven,omitempty"`
	// CtOCPCConversionsDetail118Fourteen 付费观剧14日金额（转化时间）
	CtOCPCConversionsDetail118Fourteen float64 `json:"ctOCPCConversionsDetail118Fourteen,omitempty"`
	// CtOCPCConversionsDetail118Thirty 付费观剧30日金额（转化时间）
	CtOCPCConversionsDetail118Thirty float64 `json:"ctOCPCConversionsDetail118Thirty,omitempty"`
}
